### ISSUE TITLE
QAQ can u update it to the last defs?

### ISSUE THREAD

**Issue by Yuyuko-sama** [Fukki/Tuwang#1]
S_DUNGEON_EVENT_MESSAGE v2
S_ACTION_STAGE v7
S_LOAD_TOPO v3
S_INSTANT_MOVE v3

thanks

**Comment by Yuyuko-sama** [comment]
also has this problem :

[01:05:10 GMT+0800] ERROR tera-proxy-game: [dispatch] handle: error running hook for S_ACTION_STAGE<4>
hook: actionStageHandler in Tuwang
data: { gameId: Long { low: 841598, high: 819200, unsigned: true },
  loc: Vec3 { x: 49142.3359375, y: -10107.642578125, z: -175 },
  w: 0,
  templateId: 1005,
  skill: 309265596,
  stage: 1,
  speed: 0,
  id: 1065353216,
  unk1: -6.18344354843315e+35,
  unk2: false,
  dest:
   Vec3 {
     x: 5.831554006032442e-39,
     y: 49142.3359375,
     z: -10107.642578125 },
  target: Long { low: -1020329984, high: 840078, unsigned: true },
  movement: [] }
error: Cannot read property 'time' of null
    at Move (E:\CaaliTeraProxy\bin\node_modules\Tuwang\index.js:94:15)
    at Dance (E:\CaaliTeraProxy\bin\node_modules\Tuwang\index.js:117:5)
    at Object.actionStageHandler [as callback] (E:\CaaliTeraProxy\bin\node_modules\Tuwang\index.js:154:5)

**Comment by Fukki** [comment]
just allow tuwang skill only :/

**Comment by Yuyuko-sama** [comment]
can u update defs ?0.0

**Comment by Fukki** [comment]
maybe cant because skill ID version 4 and 7 has different format
if need to update new def need to find new skill id too
ps. maybe cant block skill 309265596 need this for tab to first color

**Comment by Yuyuko-sama** [comment]
yea...that's aids

**Comment by Fukki** [comment]
need 309265596 for tab to first color

**Comment by Fukki** [comment]
it should be fix now
the problem from location event.time has null in sometime

**Comment by Yuyuko-sama** [comment]
Skill id:A623:1104
templateId id:1001
Skill id:A623:1104
templateId id:1002
Skill id:A623:1212
templateId id:1005
Skill id:A623:1212
templateId id:1006
Skill id:A623:1104
templateId id:1003
Skill id:A623:1212
templateId id:1007
Skill id:A623:1104
templateId id:1004
Skill id:A623:1212
templateId id:1005
Skill id:A623:1212
templateId id:1006
Skill id:A623:1212
templateId id:1008
Skill id:A623:1212
templateId id:1007
Skill id:A623:1212
templateId id:1005
Skill id:A623:1212
templateId id:1006
Skill id:A623:1212
templateId id:1008
Skill id:A623:1212
templateId id:1007
Skill id:A623:1212
templateId id:1005
Skill id:A623:1212
templateId id:1006
Skill id:A623:1212
templateId id:1008
Skill id:A623:1212
templateId id:1007
Skill id:A623:1103
templateId id:1001
Skill id:A623:1103
templateId id:1002
Skill id:A623:1212
templateId id:1005
Skill id:A623:1212
templateId id:1006
Skill id:A623:1103
templateId id:1003
Skill id:A623:1212
templateId id:1008
Skill id:A623:1103
templateId id:1004
Skill id:A623:1212
templateId id:1007
> Skill id:A623:12
templateId id:1005
Skill id:A623:1212
templateId id:1006
Skill id:A623:1109
templateId id:1005
Skill id:A623:1212
templateId id:1008
Skill id:A623:1110
templateId id:1006
Skill id:A623:1111
templateId id:1007
Skill id:A623:1212
templateId id:1007
Skill id:A623:1112
templateId id:1008
Skill id:A623:1212
templateId id:1005
Skill id:A623:1212
templateId id:1006
Skill id:A623:1212
templateId id:1008

**Comment by Yuyuko-sama** [comment]
I had logged those with S_ACTION_STAGE v7 0.0

**Comment by Fukki** [comment]
dont know how to use event.skill in new format :/

**Comment by Yuyuko-sama** [comment]
me too,only know use event.skill.id instead of event.skill = =

**Comment by Fukki** [comment]
btw the error should be fix now in my last commit still old def
i will update to new def again if know how to use this :x

**Comment by Yuyuko-sama** [comment]
pink jump:
Skill id:A623:1103
templateId id:1001

pink zone light:
Skill id:A623:1109
templateId id:1005
--------------------------------
green jump:
Skill id:A623:1103
templateId id:1002

green zone light:
Skill id:A623:1110
templateId id:1006
-------------------------------
red jump light:
Skill id:A623:1103
templateId id:1003

red zone light:
Skill id:A623:1111
templateId id:1007
--------------------------------
blue jump light:
Skill id:A623:1103
templateId id:1004

blue zone light:
Skill id:A623:1112
templateId id:1008

**Comment by Yuyuko-sama** [comment]
oh，I just found a better way to log those things hahahaha
'use strict'

const path = require('path'),
    fs = require('fs')

module.exports = function PlayerLogger(mod) {
    let file = path.join(__dirname, '..', '..', 'tuwang-logs' + Date.now() + '.log');
    let enabled = false;
	let old_skill_id;
	let old_template_id;
	
	mod.hook('S_ACTION_STAGE', 4, e => {
		old_skill_id = e.skill,
		old_template_id = e.templateId
	});
    mod.hook('S_ACTION_STAGE', 7, e => {
        if(enabled) {
            console.log(`Skillid :  ${e.skill.id}`+` | `+`old :  ${old_skill_id}`);
			console.log(`templateId :  ${e.templateId}`+` | `+`old :  ${old_template_id}`);
			console.log('________________________________');
            fs.appendFileSync(file,`Skillid :  ${e.skill.id}  |  old :  ${old_skill_id}\n`);
			fs.appendFileSync(file,`templateId :  ${e.templateId}  |  old :  ${old_template_id}\n`);
			fs.appendFileSync(file,`________________________________\n`);
        }
    });
    mod.command.add('loggeron', () => {
        enabled = !enabled;
        mod.command.message(`tuwang Logger ${enabled ? 'en' : 'dis'}abled`)
    })
}

**Comment by Yuyuko-sama** [comment]
[tuwang-logs1537012065864.log](https://github.com/Fukki/Tuwang/files/2385684/tuwang-logs1537012065864.log)

**Comment by Fukki** [comment]
ready fix just need test now before commit
![image](https://user-images.githubusercontent.com/26898177/45586383-e1039300-b920-11e8-81b0-93209926f11c.png)

**Comment by Yuyuko-sama** [comment]
have a quest,why there are so many useless skill ids in script = =,cause when I checking in log,I can't find those ids

**Comment by Fukki** [comment]
frog dance have 2 ID and 8 ID for floor light

**Comment by Fukki** [comment]
have problem C_PLAYER_LOCATION ,5 server side not move :/

**Comment by Fukki** [comment]
ok, it's work now thank for help :x

**Comment by Yuyuko-sama** [comment]
Thanks♪(･ω･)ﾉ
